### ISSUE TITLE
Step 5 of "is valid" doesn't make sense

### ISSUE THREAD

**Issue by garykac** [w3c/staticrange#6]
_From @bzbarsky on April 13, 2017 16:10_

Step 5 says:

> If sr’s collapsed is not equal to the result of calling is collapsed with sr,

But the return value of "collapsed" is defined to be the result of executing "is collapsed".  So the two booleans are always the same, by definition...

_Copied from original issue: garykac/staticrange#8_

**Comment by garykac** [comment]
Originally, I was thinking of "collapsed" as a cached value that could be out of sync with the proper value (calculated by "is collapsed").
But you're right that it's confusing (and the fact that it might be a cached value shouldn't be exposed here).

I'll be removing that line. Thanks!

**Comment by bzbarsky** [comment]
> that could be out of sync with the proper value (calculated by "is collapsed").

That can only happen if a StaticRange's endpoints can be mutated, right?
